### PR TITLE
Made the script file into a proper .livecodescript file

### PR DESCRIPTION
**Pull request by macMikey**
1) Changed the suffix to ".livecodescript"
2) Added the "script" header line.

### CODE REVIEW

**Comment by derbrill** [comment]
I don't know what I did, but suddenly your pull request conflicts with the master branch... I need to figure out how to resolve this.

**Comment by macMikey** [comment]
What conflict are you seeing?

**Comment by angerangel** [comment]
Please close this or give me write access.

**Comment by derbrill** [comment]
To be frank, I have no idea how to close this / resolve the conflict...

**Pull request closed without merging**
